# Generated by Django 4.2.6 on 2023-11-11 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0003_alter_dishtype_options_dishtype_related_dishes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dishtype',
            name='related_dishes',
        ),
    ]
