# Generated by Django 4.2.6 on 2023-11-21 20:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("kitchen", "0005_ingredient"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dish",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="ingredient",
            options={"ordering": ["name"]},
        ),
        migrations.DeleteModel(
            name="Cook",
        ),
    ]
